# Generated by Django 6.1 on 2026-08-21 02:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_seed_roles_permissions"),
        ("catalog", "0001_initial"),
        ("scholarships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=30, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            (
                                "additional_info_required",
                                "Additional Information Required",
                            ),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("resubmission_required", "Resubmission Required"),
                        ],
                        default="not_started",
                        max_length=30,
                    ),
                ),
                (
                    "declaration_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_remarks", models.TextField(blank=True)),
                (
                    "rejection_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("invalid_document", "Invalid document"),
                            ("expired_document", "Expired document"),
                            ("missing_document", "Missing document"),
                            ("information_mismatch", "Information mismatch"),
                            ("unclear_document", "Unclear document"),
                            (
                                "info_correction_needed",
                                "Student information requires correction",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rejection_detail", models.TextField(blank=True)),
                (
                    "assigned_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to="accounts.officer",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decided_applications",
                        to="accounts.officer",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="scholarships.scholarship",
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=30)),
                ("to_status", models.CharField(max_length=30)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="verification.application",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "application_status_history",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("storage_key", models.CharField(max_length=500)),
                ("original_filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("file_size_bytes", models.PositiveIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Scan pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected — quarantined"),
                            ("error", "Scan error"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("scan_completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
                "ordering": ["submitted_document", "version_number"],
            },
        ),
        migrations.CreateModel(
            name="DocumentReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("needs_clarification", "Needs clarification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_reviews",
                        to="accounts.officer",
                    ),
                ),
                (
                    "document_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="verification.documentversion",
                    ),
                ),
            ],
            options={
                "db_table": "document_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_mandatory", models.BooleanField(default=True)),
                (
                    "accepted_file_types",
                    models.JSONField(
                        default=list, help_text='e.g. ["pdf", "jpg", "jpeg", "png"]'
                    ),
                ),
                ("max_file_size_bytes", models.PositiveIntegerField(default=5242880)),
                (
                    "renewal_policy",
                    models.CharField(
                        choices=[
                            ("one_time", "Submitted once, never expires"),
                            (
                                "per_academic_year",
                                "Must be renewed every academic year",
                            ),
                            ("fixed_validity_days", "Expires N days after issue"),
                        ],
                        default="one_time",
                        max_length=20,
                    ),
                ),
                (
                    "validity_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Only used when renewal_policy = fixed_validity_days",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="catalog.country",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="catalog.institution",
                    ),
                ),
                (
                    "scholarship_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="catalog.scholarshiptype",
                    ),
                ),
            ],
            options={
                "db_table": "required_documents",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubmittedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending review"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("needs_clarification", "Needs clarification"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_documents",
                        to="verification.application",
                    ),
                ),
                (
                    "current_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="verification.documentversion",
                    ),
                ),
                (
                    "required_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="submitted_documents",
                        to="verification.requireddocument",
                    ),
                ),
            ],
            options={
                "db_table": "submitted_documents",
            },
        ),
        migrations.AddField(
            model_name="documentversion",
            name="submitted_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="verification.submitteddocument",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "in_progress",
                            "submitted",
                            "under_review",
                            "additional_info_required",
                            "resubmission_required",
                        ],
                    )
                ),
                fields=("scholarship",),
                name="one_open_application_per_scholarship",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="submitteddocument",
            unique_together={("application", "required_document")},
        ),
        migrations.AlterUniqueTogether(
            name="documentversion",
            unique_together={("submitted_document", "version_number")},
        ),
    ]
