# Generated by Django 6.1 on 2026-08-21 02:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_email_snapshot", models.EmailField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login.success", "Login succeeded"),
                            ("login.failure", "Login failed"),
                            ("logout", "Logout"),
                            ("account.activated", "Account activated"),
                            ("password.reset_requested", "Password reset requested"),
                            ("password.reset_completed", "Password reset completed"),
                            ("document.uploaded", "Document uploaded"),
                            ("document.deleted", "Document deleted"),
                            ("document.viewed", "Document viewed"),
                            ("document.reviewed", "Document reviewed"),
                            ("application.submitted", "Application submitted"),
                            ("application.viewed", "Application viewed"),
                            ("application.approved", "Application approved"),
                            ("application.rejected", "Application rejected"),
                            (
                                "application.info_requested",
                                "Additional information requested",
                            ),
                            ("application.reassigned", "Application reassigned"),
                            ("application.resubmitted", "Application resubmitted"),
                            ("export.generated", "Export generated"),
                            (
                                "requirement.configured",
                                "Document requirement configured",
                            ),
                            ("role.permission_changed", "Role/permission changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_logs_target__9fc8de_idx",
                    ),
                ],
            },
        ),
    ]
