# Generated by Django 6.1 on 2026-08-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login.success", "Login succeeded"),
                    ("login.failure", "Login failed"),
                    ("logout", "Logout"),
                    ("account.activated", "Account activated"),
                    (
                        "activation.identity_verification_failed",
                        "Activation identity verification failed",
                    ),
                    (
                        "activation.duplicate_blocked",
                        "Duplicate activation attempt blocked",
                    ),
                    ("activation.code_sent", "Verification code sent"),
                    ("activation.code_resent", "Verification code resent"),
                    ("activation.code_verified", "Verification code verified"),
                    ("activation.code_failed", "Verification code attempt failed"),
                    ("password.reset_requested", "Password reset requested"),
                    ("password.reset_completed", "Password reset completed"),
                    ("document.uploaded", "Document uploaded"),
                    ("document.deleted", "Document deleted"),
                    ("document.viewed", "Document viewed"),
                    ("document.reviewed", "Document reviewed"),
                    ("application.submitted", "Application submitted"),
                    ("application.viewed", "Application viewed"),
                    ("application.approved", "Application approved"),
                    ("application.rejected", "Application rejected"),
                    ("application.info_requested", "Additional information requested"),
                    ("application.reassigned", "Application reassigned"),
                    ("application.resubmitted", "Application resubmitted"),
                    ("export.generated", "Export generated"),
                    ("requirement.configured", "Document requirement configured"),
                    ("role.permission_changed", "Role/permission changed"),
                ],
                max_length=50,
            ),
        ),
    ]
